name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker checkout
      uses: actions/checkout@v4

    - name: Loguearse en docker
      uses: docker/login-action@v3.3.0
 
      with:
  
       username: ${{ secrets.DOCKER_USER }}
    
       password: ${{ DOCKER_TOKEN }}
       

    - name: Construyendo la imagen 
      run: docker build -t alexandro2/calculadora:latest .
      
    - name: Subiendo imagen
      run: docker push ${{ secrets.DOCKER_USER }}/calculadora:latest
  
