name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker checkout
      uses: actions/checkout@v4

    - name: Loguearse en docker
      run: |
        echo " Logueandose..."
        docker login -u ${{ DOCKER_USER }} -p ${{ DOCKER_TOKEN }}

    - name: Construyendo la imagen 
      run: docker build -t alexandro2/calculadora:latest .
      
    - name: Subiendo imagen
      run: docker push ${{ secrets.DOCKER_USER }}/calculadora:latest
  
