name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker checkout
      uses: actions/checkout@v4

    - name: Loguearse en docker
      uses: docker/login-action@v3.3.0
 
      with:
  
       username: ${{ secrets.DOCKER_USER }}
    
       password: ${{ secrets.DOCKER_TOKEN }}
       

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64  
        tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
