name: Docker Image CI

on:
  push:
    branches: [ "master" ]


jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Instalar las dependencias
      run: composer install 
    
    - name: tests
      run: vendor/bin/phpunit --testdox tests

    

  build:

    needs: tests

    runs-on: ubuntu-latest

    steps:
    - name: Docker checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Loguearse en docker
      uses: docker/login-action@v3.3.0
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_TOKEN }}
       
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64  
        tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
